# Change these first
owner: xlabs # Your GitHub organization or username, where this repository lives
repo: app-status # The name of this repository

sites:
  - name: Portal Bridge
    url: https://portalbridge.com
    assignees:
      - sebastianscatularo
      - yuli-ferna
  - name: USDC Bridge
    url: https://portalbridge.com/usdc-bridge/
    assignees:
      - sebastianscatularo
      - yuli-ferna
  - name: Wormholescan
    url: https://wormholescan.io
    assignees:
      - valentinoConti
  - name: Wormholescan API
    url: https://api.wormholescan.io/api/v1/health

  - name: Solana
    url: https://vaa-status-check.netlify.app/network/1
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Ethereum
    url: https://vaa-status-check.netlify.app/network/2
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Terra
    url: https://vaa-status-check.netlify.app/network/3
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: BSC
    url: https://vaa-status-check.netlify.app/network/4
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Polygon
    url: https://vaa-status-check.netlify.app/network/5
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Avalanche
    url: https://vaa-status-check.netlify.app/network/6
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Oasis
    url: https://vaa-status-check.netlify.app/network/7
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Algorand
    url: https://vaa-status-check.netlify.app/network/8
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Fantom
    url: https://vaa-status-check.netlify.app/network/10
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Karura
    url: https://vaa-status-check.netlify.app/network/11
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Acala
    url: https://vaa-status-check.netlify.app/network/12
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Klaytn
    url: https://vaa-status-check.netlify.app/network/13
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Celo
    url: https://vaa-status-check.netlify.app/network/14
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Near
    url: https://vaa-status-check.netlify.app/network/15
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Moonbeam
    url: https://vaa-status-check.netlify.app/network/16
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Terra2
    url: https://vaa-status-check.netlify.app/network/18
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Injective
    url: https://vaa-status-check.netlify.app/network/19
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Sui
    url: https://vaa-status-check.netlify.app/network/21
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Aptos
    url: https://vaa-status-check.netlify.app/network/22
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Arbitrum
    url: https://vaa-status-check.netlify.app/network/23
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Optimism
    url: https://vaa-status-check.netlify.app/network/24
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Xpla
    url: https://vaa-status-check.netlify.app/network/28
    __dangerous__body_degraded: '"status":"warning"'
  - name: Base
    url: https://vaa-status-check.netlify.app/network/30
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Sei
    url: https://vaa-status-check.netlify.app/network/32
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'
  - name: Sei
    url: https://vaa-status-check.netlify.app/network/3104
    headers:
      - "accept: application/json"
    __dangerous__body_degraded: '"status":"warning"'

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /app-status
  logoUrl: https://raw.githubusercontent.com/sebastianscatularo/app-status/master/assets/xlabs.svg
  faviconSvg: https://raw.githubusercontent.com/sebastianscatularo/app-status/master/assets/xlabs.svg
  name: xLabs Apps Status
  ##introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  ##introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /app-status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
i18n:
  footer: xLabs Apps Status, powered by [Upptime](https://upptime.js.org)
